services:
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "39092:29092" # external (host) - 29092 dipakai project lain
    volumes:
      - kafka_data:/var/lib/kafka/data
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  kafka-init:
    image: apache/kafka:3.7.0
    container_name: kafka-init
    depends_on:
      - kafka
    entrypoint: ["/bin/sh", "-c"]
    command:
      - >
        until /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092
        --create --if-not-exists --topic scan-logs --partitions 1 --replication-factor 1;
        do sleep 2; done
    restart: "no"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8090:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  clamav:
    image: clamav/clamav-debian:latest
    container_name: clamav

    ports:
      - "3310:3310"

    volumes:
      - clamav-db:/var/lib/clamav

    environment:
      CLAMD_STARTUP_TIMEOUT: 300

    healthcheck:
      test: ["CMD-SHELL", "clamdscan --ping=5 || exit 1"]

volumes:
  clamav-db:
  kafka_data:
